defaults: &defaults
  freeagent_id:          <%= ENV["FREEAGENT_ID"]                       %>
  freeagent_secret:      <%= ENV["FREEAGENT_SECRET"]                   %>
  freeagent_env:         <%= ENV["FREEAGENT_ENV"]         || "sandbox" %>
  aws_access_key_id:     <%= ENV["AWS_ACCESS_KEY_ID"]                  %>
  aws_region:            <%= ENV["AWS_REGION"]                         %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"]              %>
  aws_bucket_name:       <%= ENV["S3_BUCKET_NAME"]                     %>

development:
  <<: *defaults
  secret_key_base: 5889027e5f8e44f89aaa3184bb3ad9d4ad894a9667ee3f02bdf804ebf1cdd4bd390947fec98d981ef4291b46cdb5a230fe0a21fc1eda588f1aea556eb654b481

test:
  <<: *defaults
  secret_key_base: b86e465b00fcde91e567da4c6ce35423426a2022a641d497e2f63974ec5e0f16ddc2c86c3ac57e096c06b29ee97b08f8c46bb669ac100a4ec130092f49036c1b

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"]                 %>
  freeagent_env:   <%= ENV["FREEAGENT_ENV"]   || "production" %>
